- babel.config.js
- packages/app/package.json
- packages/app/pages/_document.tsx
- packages/app/pages/index.tsx
- yarn.lock
Just wanna make sure I didn't mess anything up with Next.js, I followed the first guide until step 5 and then added the _document.tsx file from the second link.
https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c
https://github.com/zeit/next.js/blob/master/examples/with-styled-components/pages/_document.js
> added styled-components

- packages/app/components/Queue/QueueCard.tsx
- packages/app/components/Queue/QueueList.tsx
- packages/app/pages/queue.tsx
- packages/common/index.ts
"responsive as heck" –stanley liu 2020
> Queue list UI

- DEVELOPING.md
- ormconfig.js
- package.json
- packages/api-client/index.ts
- packages/app/package.json
- packages/app/pages/_app.tsx
- packages/app/pages/schedule.tsx
- packages/common/index.ts
- packages/server/fixtures/courseModel.yml
- packages/server/fixtures/officeHour.yml
- packages/server/package.json
- packages/server/src/api/courseRoutes.test.ts
- packages/server/src/api/courseRoutes.ts
- packages/server/src/entity/ClubModel.ts
- packages/server/src/entity/OfficeHourModel.ts
- packages/server/src/index.ts
- packages/server/src/server.ts
- packages/server/src/tasks/ICalParser.test.ts
- packages/server/src/tasks/ICalParser.ts
- packages/server/src/testUtils.ts
- packages/server/tsconfig.json
- yarn.lock
This adds:
- big calendar for the calenlolz
- our first real endpoint
- our first real fixtures
- and showcasing `useSWR` which we should use in the future to fetch data
> Ical frontend

- packages/server/src/mocks/createQuestion.ts
- packages/server/src/mocks/getCourse.ts
- packages/server/src/mocks/getQuestion.ts
- packages/server/src/mocks/taUpdateStatus.ts
the mocks were old, and were not passing typecheck. this fixes them.
> mocks typecheck

- packages/server/src/api/queueRoutes.ts
> i'm brain damaged -- alex 2020

- packages/common/index.ts
> remove comments so people are not confused

- .github/workflows/lint.yml
- .github/workflows/test.yml
- package.json
- packages/server/package.json
Create Github Actions to ensure linting and run tests. Runs on pull requests.
Also makes server tests run-in-band by default so you don't have to pass the flag
> Github Actions

- packages/app/components/Nav/LeftNavBar.tsx
- packages/app/components/Nav/NavBar.tsx
- packages/app/components/Nav/RightNavBar.tsx
- packages/app/pages/class/[cid]/queue/[qid].tsx
- packages/app/pages/class/[cid]/schedule.tsx
- packages/app/pages/class/[cid]/today.tsx
- packages/app/pages/index.tsx
Adds navbar to pages and changes URL scheme to the following:
Today: `/class/{classId}/today`
Schedule: `/class/{classId}/schedule`
Queue: `/class/{classId}/queue/{queueId}`
> Course and queue URL parameters

- packages/app/components/Queue/TAQueueList.tsx
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/server/src/question/question.controller.ts
- packages/server/src/queue/queue.controller.ts
It was throwing some errors after Nest was integrated, so Dajin and I fixed up finishing questions.
> Fixing up queue page

- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/app/pages/course/[cid]/today.tsx
> use role :)

- packages/api-client/index.ts
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/server/src/notification/notification.controller.ts
- packages/server/src/notification/notification.module.ts
- packages/server/src/notification/notification.service.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/question/question.module.ts
Remember the alamo at important.png
> TAs can notify students

- packages/app/components/Nav/Settings/Profile.tsx
- packages/app/hooks/useRoleInCourse.ts
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/app/pages/course/[cid]/today.tsx
- packages/app/pages/notifications.tsx
> isTA is GONE

- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/app/pages/course/[cid]/today.tsx
* Fixed issue when students edits his/her question and it goes back to the `Queued` status
* Popup now closes when ta click help or remove on a students Question
Shoutout @NEUDitao for catching these bugs 🐛
> Quick queue fixes

- packages/api-client/index.ts
- packages/app/components/Today/TACheckinButton.tsx
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/app/pages/course/[cid]/today.tsx
- packages/common/index.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/profile/user.entity.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/queue/queue.controller.ts
- packages/server/src/queue/queue.entity.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
- packages/server/test/__snapshots__/queue.integration.ts.snap
- packages/server/test/course.integration.ts
- packages/server/test/question.integration.ts
- packages/server/test/util/factories.ts
> Ta check in

- packages/api-client/index.ts
- packages/app/components/Queue/TAQueueList.tsx
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/server/src/course/course.controller.ts
- packages/server/src/queue/queue.controller.ts
- packages/server/test/course.integration.ts
> Ta check out

- .gitignore
- packages/app/cypress.json
- packages/app/cypress/fixtures/queue_route_with_notes.json
- packages/app/cypress/fixtures/queue_routes_no_notes.json
- packages/app/cypress/fixtures/queues.json
- packages/app/cypress/fixtures/student_profile.json
- packages/app/cypress/integration/common/login.spec.js
- packages/app/cypress/integration/ta/edit_queue_notes.spec.js
- packages/app/cypress/support/commands.js
- packages/app/cypress/support/index.js
Also mock fixtures can be created dynamically from api responses to be used for future mock api responses
> Allow for Cypress tests to be run against real or mock api

- packages/app/components/Today/OpenQueueCard.tsx
- packages/app/pages/course/[cid]/today.tsx
Adds that cool "No Staff Checked In" thing
> No TA Name is now 

- packages/app/components/Today/OpenQueueCard.tsx
> hover names on today page work

- packages/app/pages/course/[cid]/today.tsx
- packages/common/index.ts
- packages/server/src/notification/notification.controller.ts
- packages/server/src/notification/notification.service.ts
- packages/server/src/notification/phone-notif.entity.ts
When you sign up for phone numbers it now asks you if you want to sign up or not. It's kind of tricky to test but lmk if you want to see a demo/try it out for yourself.
> Twilio verification

- packages/app/components/Today/OpenQueueCard.tsx
> remove checked in staff if no staff are checked in

- packages/server/src/question/question.controller.ts
Previously the taHelped was set when the Question status was changed to `Resolved` however, this does not allow for TA's to have "ownership" over particular students they are helping at any given time. 
With this PR we'll now be able to know when TA's are currently helping a student, so in the case the TA looses connection along with their local state on the frontend, we'll still be able to know which TA's are helping which students. 
Closes #115
> Update when taHelped is set and add extra checks

- packages/app/components/Nav/NavBar.tsx
- packages/app/components/Nav/Settings.tsx
- packages/app/components/Queue/StudentPopupCard.tsx
- packages/server/fixtures/userModel.yml
Fixes:
- Navbar padding
- Navbar photo loading
- Sidebar photo loading
> User picture fixes

- packages/app/components/Queue/QuestionForm.tsx
- packages/app/components/Queue/StudentQueueCard.tsx
- packages/app/components/Queue/StudentQueueList.tsx
- packages/app/cypress/integration/student/create_question.spec.js
Also fixes wait time display in StudentQueueCard
> Create question tests

- cypress/support/index.js
- packages/common/index.ts
- packages/server/migration/1598733438768-CreateCourseSectionMappingAndRemoveUsername.ts
- packages/server/ormconfig.ts
- packages/server/src/course/course-section-mapping.entity.ts
- packages/server/src/login/course-section-mapping.entity.ts
- packages/server/src/login/login-course.service.ts
- packages/server/src/login/login.controller.ts
- packages/server/src/login/login.module.ts
- packages/server/src/profile/user.entity.ts
- packages/server/test/login.integration.ts
- packages/server/test/seed.integration.ts
- packages/server/test/util/factories.ts
Note: The username is no longer being sent to us by Khoury so the `email` is now the unique identifier for a user
Closes #218
> Update Khoury login endpoint

- packages/app/components/Today/WelcomeStudents.tsx
I think first impressions pretty important when trying to build a product that user's really enjoy, so figured I'd try to spice up the Welcome modal a little bit.
> Attempt to spice up welcome modal

- packages/app/components/Nav/NavBar.tsx
- packages/app/components/RenderEvery.tsx
- packages/app/components/Schedule/SchedulePanel.tsx
- packages/app/components/Today/TACheckinButton.tsx
- packages/app/components/common/FatalError.tsx
- packages/app/hooks/useCourse.tsx
- packages/app/hooks/useLocalStorage.ts
- packages/app/pages/course/[cid]/queue/[qid].tsx
- packages/app/pages/course/[cid]/schedule.tsx
- packages/app/pages/course/[cid]/today.tsx
This PR adds page titles in the browser tabs. This is neat for if students bookmark the page
> Page Titles

- packages/app/pages/login.tsx
The updated "Login to Office Hours" page is on the admin staging site right now (check it out [here](https://admin-alpha.khoury.northeastern.edu/students/officehourslogin/)) but will be up on prod soon! 🤞
> Hook up Login button to Khoury Admin url

- packages/server/src/question/question.controller.ts
- packages/server/test/question.integration.ts
Found this bug by spam clicking on random buttons in the UI
> Prevent TA's from helping multiple students at a time

- packages/app/components/Queue/StudentBanner.tsx
> fixed finish drafting

- README.md
I figured any student who checks out our repo out of curiosity might also be interested in Oasis
> Add Oasis info in README

- packages/server/src/course/ical.service.spec.ts
- packages/server/src/course/ical.service.ts
> Filter out non office hours events in ical parser

- packages/app/pages/login.tsx
> Add professor log in button

- packages/app/components/Nav/Settings.tsx
- packages/app/components/Queue/Student/StudentInfoCard.tsx
- packages/app/components/Queue/Student/StudentQueueList.tsx
- packages/app/components/Queue/TA/StudentPopupCard.tsx
- packages/app/components/Queue/TA/TABanner.tsx
- packages/app/components/Queue/TA/TAQueueCard.tsx
- packages/app/components/Queue/TAStatuses.tsx
- packages/app/components/Today/OpenQueueCard.tsx
- packages/app/utils/ColorUtils.ts
- packages/app/utils/NameUtils.ts
- packages/server/src/question/question.controller.ts
> changed all avatars to initials + colors

- packages/app/components/Nav/Settings.tsx
- packages/app/components/Queue/Student/StudentInfoCard.tsx
- packages/app/components/Queue/TA/StudentPopupCard.tsx
- packages/app/components/Queue/TA/TABanner.tsx
- packages/app/components/Queue/TA/TAQueueCard.tsx
- packages/app/components/Queue/TAStatuses.tsx
- packages/app/components/Today/OpenQueueCard.tsx
- packages/app/components/common/AvatarWithInitials.tsx
- packages/app/utils/ColorUtils.ts
- packages/app/utils/NameUtils.ts
a;sodifjoasdjfoasjdfoasdjofijasdo;fjasod;ifjoasdijfiosadjfoisdajfoiasdhgioashbl;kzxcnvkjzxchfvoi;ujowiuqyertopqweuriupgasdifh;aiosdkgasdfgasdfashawesdrfasdrf
> refactored and abstracted for dajimbo

- packages/server/src/notification/notification.service.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/question/question.subscriber.ts
I told myself I'd start maintaining a healthy sleep schedule someday
Next thing I knew I was implementing this
closes #295
> TAs Notified when student joins empty queue

- packages/app/components/Queue/Banner.tsx
- packages/app/components/Queue/TA/TABanner.tsx
> Adjusted TA helping button styles for clarity

- packages/app/pages/course/[cid]/today.tsx
> empty today page has text now

- packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
> midnight checkout

- packages/app/components/Schedule/SchedulePanel.tsx
- packages/server/src/login/login.controller.ts
I basically just set the default scroll to start at 8AM instead of the default of 12AM
closes #400
> Df change calendar start time

- .github/workflows/lint.yml
- cypress/integration/student/create_question.spec.js
- cypress/integration/student/delete_question.spec.js
- cypress/integration/ta/student_question.spec.js
- cypress/support/commands.js
- package.json
- packages/app/components/Nav/NotificationSettingsModal.tsx
- packages/app/components/Nav/Settings.tsx
- packages/app/components/Queue/QueueListSharedComponents.tsx
- packages/app/components/Queue/Student/StudentBanner.tsx
- packages/app/components/Queue/TA/TAQueueList.tsx
- packages/app/components/common/ErrorBoundary.tsx
- packages/app/hooks/useQuestions.ts
- packages/app/hooks/useQueue.ts
- packages/app/pages/_app.tsx
- packages/app/pages/course/[cid]/today.tsx
- packages/app/scripts/uploadSourceMapToAPM.js
- packages/server/src/backfill/backfill-phone-notifs.command.ts
- packages/server/src/notification/twilio/twilio.service.ts
- packages/server/test/course.integration.ts
- packages/server/test/login.integration.ts
- packages/server/test/util/testUtils.ts
- yarn.lock
GitHub Action now runs prettier **and commits the changes**. See 6544153b59af1d25d05afc530d3fc97f789639c9 for example. This PR is big as a result because it prettifies everything that has fallen through the cracks, but in the future, nothing un-pretty should end up in master again, even if the local post-commit hook breaks on people's computers. 
**Main impact is our GitHub diffs should be smaller and without the styling fluff, making PR reviews a lot easier.**
> Fix Prettier On GitHub

- packages/app/utils/notification.ts
- packages/server/src/course/ical.service.spec.ts
> Fix Ical Mocking

- packages/app/components/Queue/TA/TABanner.tsx
> Add info notification when putting a student into limbo

- packages/app/components/Settings/SettingsPage.tsx
- packages/app/pages/settings.tsx
> got rid of white on menu

- packages/app/components/Queue/QueueListSharedComponents.tsx
- packages/app/components/Queue/Student/StudentQueue.tsx
- packages/app/components/Queue/TA/TAQueueDetail.tsx
- packages/app/components/Queue/TA/TAQueueListDetail.tsx
- packages/app/pages/settings.tsx
- wider queue info col to fit "looking for my next student"
- student "queue" title margin
- settings page container
> List Detail Styling Tweak

- packages/server/src/course/heatmap.service.ts
Removes the hardcoded 4 from the old command and now the courseId can be specified as a positional argument
> heatmap command positional argument

- cypress/integration/ta/student_question.spec.js
> fixed this cypress test that keeps shooting people int he foot

- packages/app/components/Nav/ProfileDrawer.tsx
- packages/app/components/Settings/NotificationsSettings.tsx
- packages/app/components/Today/ReleaseNotes.tsx
> Update notion links to use info site pages instead

- packages/server/src/app.module.ts
- packages/server/src/healthcheck/healthcheck.controller.ts
- packages/server/src/healthcheck/healthcheck.module.ts
useful for the uptime robot and other things. just chekcs if healthy
> healthcheck api endpoint

- packages/app/components/Queue/TA/TAQueueListItem.tsx
> Fix Place In Line Bug

- packages/app/components/Queue/TAStatuses.tsx
- packages/app/components/Today/OpenQueueCard.tsx
- packages/server/src/login/login-course.service.ts
> Stanky Profile Picture Bugs

- .github/workflows/cypress.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- infrastructure/dev/docker-compose.yml
- infrastructure/prod/ecosystem.config.js
- package.json
- packages/app/components/Queue/QueueListSharedComponents.tsx
- packages/app/components/RenderEvery.tsx
- packages/app/hooks/useEventSource.ts
- packages/app/hooks/useQuestions.ts
- packages/app/hooks/useQueue.ts
- packages/app/package.json
- packages/app/pages/course/[cid]/today.tsx
- packages/server/package.json
- packages/server/src/app.module.ts
- packages/server/src/bootstrap.ts
- packages/server/src/sse/sse.service.ts
- packages/server/test/util/testUtils.ts
- yarn.lock
When SSE is disconnected:
- Reconnect SSE, retrying every 3 seconds.
- Have SWR refetch every 10 seconds
- Show user when the queue was last refreshed by SWR
Hopefully this makes the queue updating more reliable while also increasing user's faith in the system
> SSE Indicator and Reconnecting

- packages/api-client/index.ts
- packages/app/components/Insights/components/InsightsDisplayOptions.tsx
- packages/app/pages/course/[cid]/insights.tsx
- packages/common/index.ts
- packages/server/src/insights/insight-classes.ts
- packages/server/src/insights/insights.command.ts
- packages/server/src/insights/insights.controller.ts
- packages/server/src/insights/insights.service.spec.ts
- packages/server/src/insights/insights.service.ts
- packages/server/src/profile/profile.controller.ts
- packages/server/test/__snapshots__/insights.integration.ts.snap
- packages/server/test/insights.integration.ts
This PR makes it so that all the `small` insights will be rendered on top of the larger ones.
> Update Insights Style

- packages/server/src/admin/admin.module.ts
- packages/server/test/seed.integration.ts
> Fix hanging redis on jest

- cypress/integration/common/notification_settings.spec.js
- packages/app/components/Settings/NotificationsSettings.tsx
- packages/app/components/Settings/ProfileSettings.tsx
Noticed this minor mistake using the website
> Fix minor spelling error (sucsess -> success)

- packages/app/components/Queue/Student/QuestionForm.tsx
- packages/app/components/Queue/Student/StudentQueue.tsx
- packages/app/components/Queue/TA/TAQueueDetail.tsx
- packages/app/components/Queue/TA/TAQueueDetailButtons.tsx
- packages/server/src/question/question-fsm.ts
> Allow TA to help student while drafting

- packages/server/src/backfill/backfill-husky-emails-to-northeastern.ts
- packages/server/src/backfill/backfill.module.ts
- packages/server/src/login/login-course.service.ts
- packages/server/test/login.integration.ts
Backfill to convert husky emails to northeastern emails, and updates to backend so that only neu emails are stored when new users login through khoury.
> Husky emails to northeastern backfill

- cypress/integration/common/edit_profile.spec.js
- cypress/integration/ta/student_question.spec.js
- cypress/utils.js
- packages/app/styles/global.css
> Fix percy flake

- packages/server/src/profile/profile.controller.ts
- packages/server/test/profile.integration.ts
> Fix update preferred name bug 

- PULL_REQUEST_TEMPLATE
Creates a PR template for us to follow in the future, so we can more easily figure out what we did.
Closes (no issue since we didn't create one to track this)
> Add PR Template

- packages/app/components/Queue/TA/TAQueue.tsx
- packages/app/hooks/useTAInQueueInfo.ts
Closes [this issue](https://sentry.io/organizations/sandboxnu/issues/2208708785/?project=5557379&referrer=slack)
as well as [this one](https://sentry.io/organizations/sandboxnu/issues/2174001848/?project=5557379&referrer=slack)
and [this too](https://sentry.io/organizations/sandboxnu/issues/2206614012/?project=5557379&referrer=slack)
> Sentry Frontend Error Fix

- packages/app/utils/NameUtils.ts
Couldn't sleep, and figured that this small one-liner would be a QOL for someone
Closes #580 
Tested manually. Change your name to a name w/ initials, and look @ the Avatar
> Fixed apostrophes in initials

- packages/api-client/index.ts
- packages/app/pages/course/[cid]/insights.tsx
- packages/common/index.ts
- packages/server/src/insights/insight-classes.ts
- packages/server/src/insights/insights.controller.ts
- yarn.lock
This PR adds the ability to filter the insights data by a specified date range. 
Closes #577 
This PR was tested manually by seeding the data and trying different date ranges that include or don't include the start date of the seeded data.
> Date filters for insights page

- packages/app/pages/course/[cid]/insights.tsx
- packages/common/index.ts
- packages/server/src/insights/insight-classes.ts
- packages/server/src/insights/insights.service.spec.ts
- packages/server/test/__snapshots__/insights.integration.ts.snap
- Fixed the Average Wait Time inisght
- Updated the SimpleDisplay output types to include strings
- Updated styling and some insight display names
> Small insight fixes

- infrastructure/prod/deploy.sh
Will make future deployments go smoother
😬
> added chgrp to deploy script

- packages/server/src/seed/seed.controller.ts
ran into issues reseeding on staging -- this fixes that
Please describe how you tested this PR (both manually and wtih tests)
> let's make seeding behave as expected yeah?

- packages/server/src/queue/queue-role.decorator.ts
https://sentry.io/organizations/sandboxnu/issues/2190411427/?project=5410042&referrer=slack#exception
wasn't
> more logging

- README.md
Please include a summary of the change and which issue is fixed.
The UI is now List Detail
Please also include relevant motivation and context. 
The old README had the old view
List any dependencies that are required for this change.
None
Markdown
Visual Testing, I saw it on the page in a preview
Please describe how you tested this PR (both manually and wtih tests)
> Update the queue pic in the readme 

- cypress/integration/ta/edit_queue_notes.spec.js
- packages/app/components/Queue/QueueListSharedComponents.tsx
- packages/app/components/Queue/TA/EditQueueModal.tsx
- packages/app/components/Today/OpenQueueCard.tsx
- packages/app/package.json
- packages/server/src/seed/seed.controller.ts
- yarn.lock
Allow instructors to input new lines and links in queue notes, and have new lines display properly and links be clickable. 
Also has a fix for seeding data, where new users were being seeded with bad IDs. 
Closes #398 
> El il text area

- packages/server/src/insights/insight-classes.ts
- packages/server/src/insights/insights.service.spec.ts
I implemented the final two insights for the alpha dashboard and added tests. I am super stoked right now!
Closes #578
> Df avg helping time

- cypress/integration/ta/allow_or_disable_questions.spec.js
- package.json
* Wait for assets to load before taking a snapshot
* Remove not useful snapshots
> Small Percy Fixes

- packages/api-client/index.ts
- packages/app/components/Settings/SettingsPage.tsx
- packages/server/src/profile/profile.controller.ts
Allow users to delete their profile photo, if they have uploaded one. 
Closes #567
> Delete profile picture

- DEVELOPING.md
- README.md
- packages/server/src/backfill/README.md
Started some small docs cleanups (removing mentions of `hapi`, updating to `NestJS`, making it clearer how to run `cypress`
> some small docs cleanups

- PULL_REQUEST_TEMPLATE
> PR template wtih -> with typo fix 

- fetch_prod.sh
- infrastructure/prod/anonymize.sh
- infrastructure/prod/anonymize_sql.py
Wrote up a script to anonymize the emails, phone numbers, photoURLs, firstName and lastName of userModels in a sql dump file. This will allow us to test data insights using real data on our local machines. 
To be able to anonymize staging data, you need to: 
1. run pg_dump to create the prod.sql file
2. run the python script to anonymize the data, which is then written into a anonymized_prod.sql file. 
3. delete the original prod.sql file. 
4. scp the new anonymized_prod sql dump. 
In the future, we may write a bash script to do these steps in one command. 
Closes #620
Please describe how you tested this PR (both manually and wtih tests)
> Create anonymize prod script

- infrastructure/prod/anonymize_sql.py
Some people have spaces in their first names, so this fixes the anonymization script.
Ran script and verified that it works.
> Split on tabs in anonymize script

- packages/app/components/Today/OpenQueueCard.tsx
- packages/app/components/common/SelfAvatar.tsx
Summary: Added padding to the queue card buttons, "Edit note" & "Open Queue". Also added space between the profile circles
Please also include relevant motivation and context: Looked a bit crammed visually
List any dependencies that are required for this change: None
#325 
Please describe how you tested this PR (both manually and wtih tests)
- I tested this change manually. Below are two groups of screenshots which shows the before and after
Before:
After:
> added margin and padding for queue card buttons and profile circles

- packages/server/src/queue/queue-clean/queue-clean.service.ts
Having issues on prod w/ queue clean deleting everything. This could possibly fix it?
> could possibly fix queue clean

- packages/common/index.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/login/login.controller.ts
- packages/server/src/profile/profile.controller.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/queue/queue.controller.ts
In collaboration with the Khoury Admin team and @liustanley, this PR addresses the ability to more effectively log API errors that occur, especially in requests that cause Office Hours to go down, in order for the Khoury Admin team to better debug instances when the Office Hours application becomes offline.
> Added API Error Logs/ Request error handling

- packages/app/components/Queue/TA/TAQueueDetailButtons.tsx
- packages/app/components/Settings/SettingsPage.tsx
- packages/app/components/Today/TACheckinButton.tsx
- packages/app/hooks/useDraftQuestion.ts
- packages/app/hooks/useQueue.ts
- packages/app/pages/_app.tsx
- packages/server/migration/1598733438768-CreateCourseSectionMappingAndRemoveUsername.ts
- packages/server/migration/1601671992912-DesktopNotifCreatedAtAndName.ts
- packages/server/migration/1609225767925-AddIsProfessorQueueColumn.ts
- packages/server/migration/1613852704482-RemoveNameFromUserModel.ts
- packages/server/migration/1619126213146-AddSubmittedCourseFields.ts
- packages/server/src/course/ical.service.ts
- packages/server/src/insights/insights.service.ts
- packages/server/src/notification/desktop-notif-subscriber.ts
- packages/server/src/notification/notification.service.ts
- packages/server/src/question/question.subscriber.ts
- packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
- packages/server/test/course.integration.ts
app crashes at midnight. maybe cleaning every queue in parallel is too much and crunks postgres? either way it doesnt hurt to just clean one at a time instead.
> queue clean one at a time

- packages/api-client/index.ts
- packages/app/components/Settings/CourseOverrideSettings.tsx
- packages/app/pages/nocourses.tsx
- packages/common/index.ts
- packages/server/migration/1622310391601-SelfEnroll.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/course/course.entity.ts
- packages/server/src/login/login.controller.ts
- packages/server/src/profile/user-course.entity.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
- packages/server/test/login.integration.ts
Banner is down. In the case that something similar happens again (e.g. Khoury Admin or banner are down), allows students to still use the app.
> El banner down large scale override

- packages/app/components/About/AboutPage.tsx
Update about page for all the new members! Also move the graduated members into "past members" section
> Update about page

- packages/app/babel.config.js
- packages/app/next.config.js
- packages/app/package.json
- packages/server/webpack.config.js
- yarn.lock
Seems like next11 breaks staging, so we're just throwing in the towel and reverting back to next10. 
> Revert next11 to next10

- packages/app/components/Settings/CoursePreferenceSettings.tsx
Course preferences setting page was erroring out because it was accessing fields on an undefined object. 
> Nullcheck course object

- DEVELOPING.md
I literally made this template fuck this shit
Closes none of my issues, I'm in the top 0.05% of Olivia Rodrigo listeners baby
It hasn't
I promise you I'll do none of these things
> Update DEVELOPING.md to remove non-existent yarn:start command

- packages/app/components/Queue/Student/StudentBanner.tsx
- packages/app/components/Queue/TA/QuestionGrouping/AllQuestionsChecklist.tsx
- packages/app/components/Queue/TA/TAQueue.tsx
- packages/app/components/Queue/TA/TAQueueDetailButtons.tsx
- packages/app/hooks/useDefaultMessage.ts
- packages/app/hooks/useTeams.tsx
- up
Small refactor on how teams would be opened. Previously only checked if the room name is just "Online", but now we check if the name begins with "Online".
Closes #763
> Start teams call if room name begins with "Online"

- packages/server/migration/1639939207124-LoginFlowModels.ts
- packages/server/migration/1639939836105-LoginFlowModels.ts
- packages/server/ormconfig.ts
- packages/server/src/course/course.entity.ts
- packages/server/src/login/last-registration-model.entity.ts
- packages/server/src/login/prof-section-groups.entity.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
Updates/creates the database models outlined in our [problem doc](https://www.notion.so/sandboxnu/New-Login-Flow-42e109bacd54478a9c5e97256cd1b05b), with the exception of the semester mapping model changes which are implemented in #773 
This also depends on #773 because I need the Khoury Admin types from it. 
TODO: 
> Database models for login flow

- DEVELOPING.md
- packages/server/migration/1640912694634-RemovePendingFieldFromCourseModel.ts
- packages/server/src/course/course.entity.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
Removed the word `pending`
Closes #799.
> Remove pending field from course entity

- packages/app/components/Apply/ApplyPage.tsx
- packages/app/components/Apply/ConfirmCourses.tsx
- packages/app/components/Apply/EditCourse.tsx
- packages/app/components/Apply/SelectCourses.tsx
- packages/app/hooks/useHomePageRedirect.ts
- packages/app/pages/index.tsx
- packages/app/pages/login.tsx
- packages/app/pages/nocourses.tsx
- packages/server/src/seed/seed.controller.ts
Creates the frontend for course registration, including the apply page and the automatic redirect to the apply page. 
Closes #795 
Overview of technical changes:
- Altered `useTodayPageRedirect` hook to `useHomePageRedirect` - in addition to redirecting the user to the /today page of their default course, it will redirect the user to the /apply page if they have any pending courses in their profile
- Replaced the old course application page with the new application flow, outlined in [figma designs](https://www.figma.com/file/AXOFBPj7DEIhYyAVe9AIil/In-Progress?node-id=286%3A3474)
- This needs #801 to be merged first so the frontend can be hooked up to the course_registration endpoint
You can manually test this if you fake some admin data in …
> Course Registration FE

- packages/common/index.ts
Updated campus from string to number.
> [Login Flow] Fix KhouryDataParams campus data type

- cypress/fixtures/example.json
- cypress/integration/common/no_courses_logout.spec.js
- packages/app/pages/dev.tsx
- packages/app/pages/nocourses.tsx
A button was added to the no courses page to allow a user to log out. This will allow users that need to load new courses for the semester to clear their cookies. 
Closes #822
- [] I have commented my code where needed 
- [] I have made corresponding changes to the documentation
> No courses logout

- cypress/integration/ta/queue_check_in_check_out.spec.js
- cypress/integration/ta/queue_disable.spec.js
- packages/app/pages/course/[cid]/today.tsx
- packages/server/src/alerts/alerts.service.spec.ts
- packages/server/test/alerts.integration.ts
Update the empty today page to be more relevant with changes to how queues are opened.
Closes #756 
> Refactor empty today page message

- packages/server/src/course/heatmap.service.spec.ts
- packages/server/src/course/heatmap.service.ts
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
> heatmap fix to switch from ohmodel to taevents

- packages/common/index.ts
- packages/server/migration/1644174303826-purge_ohmodel.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/course/course.entity.ts
- packages/server/src/course/heatmap.service.spec.ts
- packages/server/src/course/heatmap.service.ts
- packages/server/src/course/ical.service.spec.ts
- packages/server/src/course/ical.service.ts
- packages/server/src/course/office-hour.entity.ts
- packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
- packages/server/src/queue/queue.entity.spec.ts
- packages/server/src/queue/queue.entity.ts
- packages/server/src/queue/queue.service.ts
- packages/server/src/seed/seed.controller.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
- packages/server/test/course.integration.ts
- packages/server/test/question.integration.ts
- packages/server/test/queue.integration.ts
- packages/server/test/seed.integration.ts
- packages/server/test/util/factories.ts
purges the oh model -- removes links from corresponding entities that had references to Model.  Also refactored certain behaviors contingent on oh models like shouldCleanQueue, arethereofficehoursrightnow, etc. Also refactored all the tests and updated snapshots so they pass.  Cypress tests also work (verified).
Closes #736 
> Nb purge ohmodel

- cypress/integration/ta/queue_check_in_check_out.spec.js
- packages/app/components/Today/TACheckinButton.tsx
- packages/common/index.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
- packages/server/test/course.integration.ts
- yarn.lock
Remove queue cleaning via TA checkout and leaving it up to the cron job to do it all instead. This involves removing the modal that pops up when the last ta leaves a queue and any related logic tied to this.
Closes #840 
> Remove queue clean on checkout

- packages/api-client/index.ts
- packages/app/components/Queue/Student/StudentQueue.tsx
- packages/app/pages/index.tsx
- packages/common/index.ts
- packages/server/migration/1645995817187-section_group_name_null.ts
- packages/server/src/alerts/alerts.service.ts
- packages/server/src/course/course.controller.ts
- packages/server/src/course/course.entity.ts
- packages/server/src/course/course.service.spec.ts
- packages/server/src/course/course.service.ts
- packages/server/src/question/question.controller.ts
- packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
- packages/server/src/queue/queue-clean/queue-clean.service.ts
- packages/server/test/__snapshots__/course.integration.ts.snap
- packages/server/test/course.integration.ts
- packages/server/test/question.integration.ts
- packages/server/test/util/factories.ts
- yarn.lock
Update hybrid queues with master. making this a PR because I had to address merge conflicts and wanna make sure the CI still passes
> Merge master

- packages/server/src/resources/resources.service.ts
For some reason, calendar files for old semesters aren't getting deleted on prod :/ I've confirmed the feature works locally though, so the only thing I can think of is to add a bunch more logs to try to see what's happening on prod.
> Add logging to calendar cron job

- packages/app/components/Queue/QueueListSharedComponents.tsx
Received a complaint about the bright orange color of clear queue button. Changed it to an red outlined color.
Closes #888 
Tested manually...
> Change Clear Queue Button Color

- .github/workflows/deploy.yml
- .github/workflows/enforce-migration.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> update node version in GH actions to v14

- packages/app/components/Settings/TACheckInCheckOutTimes.tsx
Adds a download button to the check-in checkout page for profs. Downloads file as a JSON blob with the format 
```
[{
"name": "Will Stenzel",
"checkinTime": "2022-11-13T18:14:45.545Z",
"checkoutTime": "2022-11-14T05:00:00.000Z",
"forced": true,
"inProgress": false,
"numHelped": 0
}]
```
Tested locally
> add download button
