sandboxnu/office-hours

packages/app/components/Queue/QuestionForm.tsx
packages/app/components/Queue/QueueList.tsx
packages/app/pages/_app.tsx
packages/app/pages/queue/index.tsx
packages/app/pages/queue/join.tsx
packages/app/styles/global.css

**this should only be merged to master after #4 is merged**
add the form page UI + state management for joining the queue.
note: we couldn't find an easy way to check for (and warn) the user when they try to navigate away from the join page (to warn them they would lose their spot in the queue). our solution to this was to throw an error in the callback, which is not optimal (lmao). 
any suggestions welcome.

Join queue

---

babel.config.js
packages/api-client/index.ts
packages/app/components/Today/OpenQueueCard.tsx
packages/app/package.json
packages/app/pages/schedule.tsx
packages/app/pages/today.tsx
packages/common/index.ts
packages/server/src/api/courseRoutes.ts
packages/server/src/joi.ts
yarn.lock

We:
- created the today page :) (and kinda on mobile but not really but at least it stacks 🥳 )
- created the endpoint /v1/courses/{course_id}/queue
- moved /v1/courses/{course_id}/ -> same but with schedule at the end
- removed the title header from the calendar because the navbar will have it one day
- made a temp navbar
- made some probably questionable frontend maneuvers. pls guide us senpai
- updated some types but ignore `yarn tsc`

Creates today page and uses MOCK DATA (not fixture) for backend currently

---

packages/app/components/Queue/StudentInfoCard.tsx
packages/app/components/Queue/StudentPopupCard.tsx
packages/app/components/Queue/TAQueueList.tsx
packages/common/index.ts
packages/server/fixtures/questionModel.yml
packages/server/fixtures/userCourseModel.yml
packages/server/fixtures/userModel.yml
packages/server/src/profile/user.entity.ts
packages/server/src/question/question.entity.ts
packages/server/test/__snapshots__/course.integration.ts.snap
packages/server/test/__snapshots__/question.integration.ts.snap
packages/server/test/__snapshots__/queue.integration.ts.snap

This PR makes some changes to UserModel and QuestionModel that we were missing before, if I messed up anything Nest-wise pls lmk. I made it so that if a question is marked as online, clicking Help will automatically open a chat with the student, but this behavior can be changed easily.
To test:
1. Seed the database
2. Login as TA
3. Click on second question in queue
4. Click help
Closes #51

Open Microsoft Teams chat when helping a student

---

packages/api-client/index.ts
packages/app/components/Today/OpenQueueCard.tsx
packages/common/index.ts
packages/server/src/queue/queue.entity.ts

We decided that for now we won't be having a notion of "time" for a queue because it was a bit complicated to get right. It could be implemented later so I added a comment with the commit hash so we can reference back to it.

Remove queue time

---

packages/server/src/question/question.subscriber.ts

When you go from 3 people in the queue, to 2 people in the queue, the subscriber throws an error because `third` is undefined.

Fix 3rd in Queue Notif Error

---

packages/server/src/queue/queue.service.ts

Looks like we don't need this query. 
Getting questions for the queue comes from the `/queues/:queue_id/questions` endpoint

Remove unnecessary db query

---

packages/app/components/Nav/NotificationSettingsModal.tsx
packages/server/src/notification/notification.service.ts
packages/server/src/profile/profile.controller.ts
packages/server/src/question/question.controller.ts
packages/server/test/question.integration.ts

We weren't correctly checking for existing `DesktopNotifModels` before which resulted in notifications being duplicated, this fixes that

Fix duplicate notifications bug

---

.github/workflows/deploy.yml
infrastructure/prod/ecosystem.config.js
packages/app/pages/dev.tsx

Deploying to staging/prod can take 5-10 minutes. Most of this is running `yarn build` which is super slow on the VMs and can even affect webapp performance. Solution is to build first, then push the built files to where we want to deploy them. 
_(we could do this with docker, but it's much simpler this way)_
PM2 pulls down from git, so we're just gonna host the built files **on a Git branch**. 
1. The `dist` branch has a different `.gitignore` that lets the built js files get committed.
2. The `deploy` GitHub Action runs `yarn build` and commit/pushes the result to the `dist` branch
3. Then, the action runs pm2 deploy the same way as before, except `ecosystem.config.js` gets `dist` instead of `master`, and doesn't run build in the `pre-deploy`.
You can no longer run `yarn deploy …

Push Built Files to Deployment Targets

---

.github/workflows/cypress.yml
.github/workflows/enforce-migration.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Using https://github.com/marketplace/actions/npm-or-yarn-install-with-caching to leverage the GitHub Actions cache on yarn install. Brings `yarn install` time on Actions from ~1m20s to ~50s. It's not a huge leap because we still end up linking dependencies. Not sure if that can be skipped, but a 30s speedup on all actions may help us deploy quick and more confidently during incidents.

Attempt to Speed up GitHub Actions by Caching node_modules

---

packages/app/components/Nav/Settings.tsx
packages/app/pages/dev.tsx
packages/common/index.ts
packages/server/src/bootstrap.ts
packages/server/src/non-production.guard.ts

**READ THIS PR CAREFULLY**
If a boolean is miffed somewhere in this PR we may open up dev features into prod :| 
The goal here is to avoid the isProd logic being spread out everywhere and get it right, in one spot. Also *actually* hide the dev panel correctly.
I'm starting to think it might be better to have an isProd on the frontend and one on the backend, cause reading process.env inside `common` is just a bit scary. Would like people's thoughts!

Better IsProd Checking

---

packages/api-client/index.ts
packages/app/components/Nav/NotificationSettingsModal.tsx
packages/app/package.json
packages/app/public/service-worker.js
packages/app/utils/notification.ts
packages/common/index.ts
packages/server/migration/1601671992912-DesktopNotifCreatedAtAndName.ts
packages/server/src/notification/desktop-notif.entity.ts
packages/server/src/notification/notification.controller.ts
packages/server/src/notification/notification.service.ts
packages/server/src/profile/profile.controller.ts
packages/server/test/__snapshots__/profile.integration.ts.snap
packages/server/test/notif.integration.ts
packages/server/test/profile.integration.ts
yarn.lock

- Added code to send browser/OS info when registering for desktop notif.
- Added endpoint to delete your desktopnotif
- Return list of desktopnotifs in profile endpoint (redacted the sensistive info)
- Frontend just renders a list accordingly

Per-Device Notifs

---

cypress/integration/ta/allow_or_disable_questions.spec.js
cypress/integration/ta/queue_check_in_check_out.spec.js
packages/app/components/Queue/Student/StudentQueueList.tsx

Notice how when we save the question the queue list updates correctly but the student banner does not.

Update mutation to fix rendering bug

---

packages/api-client/index.ts

The notify endpoint is looking for a `POST` request but we were sending it a `PATCH`
https://github.com/sandboxnu/office-hours/blob/95c110a82ec2b6e14dc6e7ee0d587d0b98b5c961/packages/server/src/question/question.controller.ts#L220

Change notify request method to match the backend

---

cypress/utils.js

Noticed many cypress flakes were a result of the defaultCourseRedirect sending the browser to /today **after** cypress called .visit on the queue page, so we'd end up stuck on the today page, when the test expected us to be on the queue page. This waits for that redirect before proceeding. Thank the lord for the utils file, this is a tiny change.

Maybe Fix Cypress Flake

---

packages/server/migration/1606609022417-AddFirstLastName.ts
packages/server/src/backfill/backfill-phone-notifs.command.ts
packages/server/src/backfill/backfill.module.ts
packages/server/src/backfill/separate-first-last-names.command.ts
packages/server/src/login/login.controller.ts
packages/server/src/profile/user.entity.ts
packages/server/src/queue/__snapshots__/queue.service.spec.ts.snap
packages/server/test/__snapshots__/course.integration.ts.snap
packages/server/test/__snapshots__/question.integration.ts.snap

El names migration

---

packages/server/src/course/heatmap.service.ts

The array rotate method on the backend on the heatmap was crunked. I just reverted it back to what it used to be (but eslint doesn't like it).

rotation fix for heatmap

---

package.json

Give docker compose a project name. this prevents clashing with other projects. namely, i can't develop on search and office hours at the same time because the docker compose resources start clashing﻿

Give docker project name

---

.github/workflows/cypress.yml
.github/workflows/deploy.yml
.github/workflows/test.yml
infrastructure/dev/docker-compose.yml
infrastructure/prod/ecosystem.config.js
package.json
packages/app/pages/course/[cid]/today.tsx
packages/server/package.json
packages/server/src/app.module.ts
packages/server/src/bootstrap.ts
packages/server/src/queue/queue-sse.service.ts
packages/server/src/sse/sse.service.ts
packages/server/test/util/testUtils.ts
yarn.lock

Use PM2 to run 2 instances of the app in cluster mode, load balancing between them. `prod:start` then uses `reload` instead of `restart`, which will restart them one at a time, waiting for one to come up before starting the next. This results in having 1 instance of the app up at all times.
We will now run 2 instances of the app in parallel. This will help us scale the app out horizontally in the future, to handle more users.
HOWEVER, running a system like this means we can NO LONGER persist things in memory and expect them to be the same on subsequent requests, since requests are split across multiple instances that may restart randomly. This new constraint so far just affects SSE, so much of this PR is just rerwriting SSE to use Redis to pub/sub between instances of the backend and send …

Zero Downtime

---

packages/server/migration/1609377256784-AddCourseTimezones.ts
packages/server/src/backfill/backfill-course-timezones.ts
packages/server/src/course/course.entity.ts
packages/server/src/course/heatmap.service.ts
packages/server/test/__snapshots__/course.integration.ts.snap
packages/server/test/course.integration.ts

The only thing that might be a little weird with course timezones would be queue-cleans at midnight, but we should have a productive discussion about that because courses will now have office hours throughout the day across various countries. Closes #510

Adding timezones to courses

---

cypress/integration/ta/student_question.spec.js
packages/app/components/Queue/TA/TAQueueListDetail.tsx

When the "Help Next" button is clicked it does not select the question that is TA is now helping in the list detail view. This means the TA has to click on the question in the currently helping section and then click finish helping in the question detail pane. This is not a big deal but I thought fixing it would slightly improve the UX for TAs.

Help Next slight UX improvement

---

packages/app/components/Settings/NotificationsSettings.tsx
packages/app/components/Settings/ProfileSettings.tsx

Another student mentioned that it was unclear that the "OK" button was working on the settings page because there was no feedback on the screen telling them it worked, so I added a message to help clear up the UX

Add settings confirmation message

---

packages/server/migration/1611958171853-UserCourseOverride.ts
packages/server/src/login/login-course.service.ts
packages/server/src/profile/user-course.entity.ts
packages/server/test/login.integration.ts
packages/server/test/util/factories.ts

Add an `override` field to the UserCourse model, so that UserCourses which have `override = true` will not be wiped away when re-fetching khoury data.

User course override

---

packages/server/src/course/course.controller.ts

This issue was caused by not calling the `checkIsOpen()` function if a queue was a professor queue. The `checkIsOpen()` mutates the queue by adding an `isOpen` attribute to it which is not very clear and something we should probably change in the future.

Hot fix issue with queue section not showing for professors

---

packages/server/src/queue/queue.entity.spec.ts
packages/server/src/queue/queue.entity.ts

I noticed there was an issue with checking for open office hours when the time spanned across midnight cause all of our cypress tests would randomly fail every so often. This was caused by us not accounting for the fact that the EST timezone is six hours different from UTC. With the help of @liustanley we updated the code that finds office hours to look in a wider time range to account for this.

Fix issue with checking for open office hours

---

packages/app/utils/NameUtils.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
Apparently people just don't update their browsers after 6 months or something...
Closes [sentry boi](https://sentry.io/organizations/sandboxnu/issues/2231291842/?referrer=slack)

 why aren't people updating their browsers :angy:

---

packages/common/index.ts

Instead of having an any[], we can have a strict type for an object whose keys are strings and whose values are as well. 
Closes #609 
Types Update

Removing Any From the Table and Graph Insight Types

---

packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
packages/server/src/queue/queue-clean/queue-clean.service.ts

Previously our `cleanAllQueues` function was attempting to clean only the queues which had questions with an `OpenQuestionStatus`. This meant we were not able to clean queues that had questions in `LimboStatus`. 
I decided to update the `cleanAllQueues` function to clean all queues that are attached to a course that is currently active. This we not only will we clean all the `Open` and `Limbo` status questions from the queue but we will also reset the queue notes for all the active queues (which I think we want to do). 
Closes #631 #632
Added tests to the for the `cleanAllQueues` function

Fix clean queue bug

---

packages/server/src/course/ical.service.ts

This is a one line PR that sets the retry count for our Redlock instance to 0, meaning that it will treat a failure as the resource being "locked" or (more correctly) "unavailable".
Addresses this error on [Sentry](https://sentry.io/organizations/sandboxnu/issues/2258968235/?environment=production&project=5410042&query=is%3Aunresolved)
I haven't tested this yet, but it shouldn't be a breaking change. We can verify this on staging.

Fix LockError when second server tries to scrape

---

packages/app/components/Queue/TAStatuses.tsx
packages/server/src/queue/queue.service.ts

Students can currently see the names of the other students that are being helped. I made it so that only TAs can see who other TAs are helping by anonymizing the questionsGettingHelp on the backend
**TA View**
**Student Being Helped** 
**Other Student In Course**
Closes # (issue number) #604

anonymize student helping names to other students

---

packages/server/src/queue/queue-clean/queue-clean.service.ts

Turns out the query for the previously updated queue clean cron was totally crunked so we had to revert it (whoops). This quick fix will let us clean the queue's with questions that are in the limbo state, but we'll still want to find a way to clean all active queues so we can ensure the queue notes get reset each night. 
Tested with the current `queue-clean.spec.ts` tests

Quick fix queue clean cron job

---

packages/server/package.json
packages/server/src/admin/credentialValidator.ts
packages/server/src/backfill/backfill-phone-notifs.command.ts
packages/server/src/course/course-roles.guard.ts
packages/server/src/course/ical.service.ts
packages/server/src/profile/user.entity.ts
packages/server/tsconfig.json
tsconfig.json
yarn.lock

`redlock` was added without `@types/redlock`. This also makes it so `yarn tsc` ignores `node_modules` consistently (it's kind of useless to check those), and those a little cleanup to start getting ready for strict null checking
Closes (issue number) [i have too many issues]
`yarn tsc`.

typed redlock + ignore lib in tsconfig consistently + start of strict null checking

---

packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
packages/server/src/queue/queue-clean/queue-clean.service.ts

Previously we we're cleaning the queue notes each night for the queues that were getting cleaned. However, we realized some people might want to have an announcement in the queue notes that persists over multiple days so we decided to stop clearing the queue notes during the queue clean. 
Updated automated tests

No longer clear queue notes during queue clean

---

packages/app/pages/course/[cid]/insights.tsx
packages/server/src/insights/insight-objects.ts

If there are no questions answered, the median helping/wait time is 0. 
If the network request containing an insight output is falsy, but still a value like 0, we want to render it. We only want the loading shell with undefined values. 

small insights bug fixes

---

packages/app/utils/TimeUtil.ts

Fixes #665 by displaying negative elapsed time as 0 to account for minor time differences between client and server. Prevents negative values from being displayed as the elapsed time.
Closes #665 
Has not been tested yet.

Display negative elapsed time as 0

---

packages/app/components/Today/TACheckinButton.tsx
packages/server/src/course/ical.service.spec.ts
packages/server/src/course/ical.service.ts

Changes regex for the ical office hours prefix from `OH|Hours` to `Online OH`, in preparation for our eventual move to incorporating in person OHs.
Also update the ical unit tests for the new prefix.

Change ical prefix and update tests

---

.github/workflows/cypress.yml
.github/workflows/lint.yml
.husky/pre-commit
package.json
packages/app/components/Queue/QueueListSharedComponents.tsx
yarn.lock

`Prettified Code!` has been causing a lot of trauma in the form of *forever frozen GitHub actions*. In addition, currently it is difficult to visualize lint errors until after commits are pushed, which consequently slows down our dev process. This simple PR is meant to get rid of the cursed third-party prettier GitHub action and reconfigure our current husky hook.
Adds the `lint-staged` package, as well as upgrades husky to `v.7.0.4`, which moves the husky hooks to `~./husky`, which is a collection of bash scripts that run custom commands at our disposal. The current only hook is `pre-commit`, which contains `npx lint-staged`.
`lint-staged` is configured to *supposedly* only check `.ts/.tsx` files that are staged for commit. It runs through a `prettier --write` command (which functions …

Reconfigure husky, prettier, eslint

---

packages/server/src/queue/queue.entity.ts
packages/server/test/course.integration.ts
packages/server/test/question.integration.ts
packages/server/test/queue.integration.ts

Updates queues' open status to be only based on whether there are staff checked in or not (`QueueModel.staffList` is not empty). Function `checkIsOpen` is still async, but should resolve nearly instantly since it is returning a promise that is resolved instantly.
Side Effects: queues with no staff checked in are not present anymore -- ie invisible for both the TA and the student.  That being said, TA's still have a check-in button to get into the queue.  Professor queues are immune and still visible.
Tests that relied on the old defintion of 'open' were updated (`queue.integration.ts`, `course.integration.ts`, `question.integration.ts` ) to make sure that queue is open when applicable
Closes #729 
Please describe how you tested this PR (both …

Prevent queues from opening automatically

---

.github/scripts/isMigrationNeeded.sh
packages/app/components/Queue/TA/QuestionGrouping/AllQuestionsChecklist.tsx
packages/app/components/Queue/TA/TAQueueDetailButtons.tsx
packages/app/hooks/useDefaultMessage.ts
packages/server/src/course/course.entity.ts

Adds the default teams message to Teams calls opened from a question group. 
Also tweak the logic to get the default message on the front end, so that if `includeDefaultMessage` is true but the `defaultMessage` is null, the teams call opens with no message instead of "null". I realized that this shouldn't actually happen if we do the backfill to set the defaultMessage of "hi my name is..." on everyone, but it's probably good to have the extra safety anyways. 
Closes https://github.com/sandboxnu/office-hours/issues/708
- Manual test: Set a default teams message and open a question group
- Manual test: When you delete and seed data, …

Add default teams msg to question grouping

---

packages/server/src/course/course.service.ts
packages/server/src/semester/semester.module.ts
packages/server/src/semester/semester.service.spec.ts
packages/server/src/semester/semester.service.ts
packages/server/src/semester/setCourse.command.ts

Command for mass enabling and disabling courses based on the semester (for transitioning between semesters)
command is `yarn cli semester:modsemester <mode> <season> <year>`
where: 
-  `mode` is one of `enable` or `disable`, 
- `season` is one of `Fall` `Spring` `Summer_Full` `Summer_1` or `Summer_2`
- `year` is a number
this modifies the enabled field to match `mode` (`true` for enabled, false for `disabled`).
Added a semster service `semester.service.ts` and a corresponding test file `semester.service.spec.ts`  to test on different inputs.
Note: the only kind of equality between semesters is matching `semesterId`, so in order to refer to a semester, we need to perform a lookup to get the `SemesterModel` and the specific id.  This is done with `getSemester`. 
Please include a summary of …

New setsemester command (off master)

---

cypress.json
cypress/integration/ta/queue_create_inperson_or_online.spec.js
cypress/integration/ta/queue_disable.spec.js
packages/api-client/index.ts
packages/app/components/Queue/QueueListSharedComponents.tsx
packages/app/components/Queue/Student/StudentQueue.tsx
packages/app/components/Queue/TA/TAQueue.tsx
packages/app/components/Queue/TAStatuses.tsx
packages/server/src/queue/queue.controller.ts

Adds the frontend functionality to disable queue along with a warning modal for confirmation.
Closes #734

Disable Queue

---

packages/api-client/index.ts
packages/common/index.ts
packages/server/src/course/course.controller.ts
packages/server/src/course/course.module.ts
packages/server/src/course/course.service.ts
packages/server/src/login/login-course.service.ts
packages/server/test/__snapshots__/course.integration.ts.snap
packages/server/test/course.integration.ts
packages/server/test/util/factories.ts

As part of the new login flow, this new endpoint uses a new array of `RegisterCourseParams` which allows professors to register multiple `SectionGroups` at once. (A `SectionGroup` represents a course with multiple section offerings, denoted by CRN)
- Refactors the `CourseModel` object to have a `sectionGroupName` field
- Generates `CourseSectionMappings` for each item in `sectionGroup.crns`
- Creates a `UserCourse` where professor is assigned as a user of the created course
- Updates professor's last registered semester to match the course's semester
Closes #781.
This PR was created because the [original one](https://github.com/sandboxnu/office-hours/pull/801) was closed by accident. 
New course integration test for `register_courses` endpoint.

[Login Flow] Register Course Endpoint

---

packages/app/components/Queue/QueueListSharedComponents.tsx
packages/app/components/Queue/Student/StudentQueue.tsx
packages/app/components/Queue/TA/TAQueue.tsx
packages/app/components/Today/TACheckinButton.tsx
packages/common/index.ts
packages/server/src/course/course.controller.ts
packages/server/src/course/ical.service.ts
packages/server/src/queue/queue.entity.ts
packages/server/test/course.integration.ts

updated all lookups that use the `room` field as a a key to look for non-disabled queues.  Updated course controller and ical service. Grepped across server/ to look for instances of `QueueModel.find`.  Also added indicators on disabled queues to tell the user that is queue disabled.  
Checking into a disabled queue yields a 404 on POST, added a message that propagates the error.  Also disabled the disable queue button, since the queue is disabled.
Closes #797 and #798

update QueueModel queries for isDisabled

---

packages/server/migration/1642001529143-NullableCrn.ts
packages/server/src/login/course-section-mapping.entity.ts

Past entries to the `CourseSectionMappingModel` don't have a crn, so running the migration that adds a crn column fails because the column was not nullable. This changes the `crn` column to be nullable for backwards compatibility.

Make crn column nullable

---

packages/server/src/course/course.service.ts
packages/server/test/course.integration.ts

If profs decide not to register any new courses (this can be bc another professor has already registered on their behalf), we do not set the last registered semester for them. They'll see the apply page every time they log in. 
We set the last registered semester inside the for loop when analyzing each section group in the list. This PR pulls it out of the loop, which now means if the professor does not select any courses to register, we set the lastRegisteredSemester to the current semester's Khoury code (I made a new helper to find this). 
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Please …

set lastregistered sem if no courses are registered

---

packages/app/components/Apply/EditCourse.tsx
packages/server/src/login/login-course.service.ts

this was a rookie mistake on my part - if the prof has logged in before and already had sectionGroups saved in our DB, we need to modify the entry instead of creating a new one. Otherwise you get a foreign key constraint violation. 

Prevent error if prof already has sectionGroups saved

---

packages/app/pages/index.tsx

Application now shows a loading spinner instead of flashing the no courses page temporarily when a user logs in
Makes login look a little cleaner
Closes #828
- [] I have added tests that prove my fix is effective or that my feature works

Add spinner to indicate app loading

---

packages/app/pages/index.tsx
packages/server/src/backfill/backfill-section-group-name.ts
packages/server/src/backfill/backfill.module.ts

Wrote a quick backfill to fill in the sectionGroupName column in course_model  for old cases where it's null
Allows that column to be marked non-nullable
Closes #793
- [] 
- [] Test A: Ran backfill locally through yarn cli and saw that dev table was updated correctly.

Backfill sectionGroupName

---

packages/common/index.ts
packages/server/src/queue/queue.entity.ts

Given that the checkIsOpen() method on the QueueModel now basically only depends on if there are people in the stafflist, it becomes pretty important that the stafflist relation is fetched when using this method - otherwise it returns the wrong result where it looks like the queue is not open because the stafflist array is undefined. 
I found this issue while working with Vera on #661 - the alerts service wasn't fetching the stafflist array ([now fixed](https://github.com/sandboxnu/office-hours/blob/vk-fix-fix-alerts/packages/server/src/alerts/alerts.service.ts#L29)), so alerts were getting improperly purged when the queue was actually still open. 
This PR just has the checkIsOpen() method throw an error if the staffList field doesn't exist - this isn't entirely ideal, as you won't …

Make sure staffList is fetched when using queue.checkIsOpen()

---

packages/app/pages/index.tsx

Application now shows a loading spinner instead of flashing the no courses page temporarily when a user logs in
Makes login look a little cleaner
Closes #828
- [] I have added tests that prove my fix is effective or that my feature works

Add spinner to indicate app loading again

---

packages/server/migration/1645995817187-section_group_name_null.ts
packages/server/src/course/course.entity.ts
packages/server/test/__snapshots__/course.integration.ts.snap
packages/server/test/util/factories.ts

Don't allow sectionGroupName column in Course Entity to be null
(sectionGroupName has been backfilled)
**Not sure how to test this, would I have to generate + run migrations on dev?**
**Update: generated + ran migration on dev and dev ran successfully, new tests also ran successfully after updated snapshot**

Remove nullability from sectionGroupName

---

packages/server/src/alerts/alerts.service.ts
packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
packages/server/src/queue/queue-clean/queue-clean.service.ts

Essentially, there was a bug that I didn't really catch when finishing up the alerts flow in my other pr. The bug was that some alerts were never resolved after a queue closes at midnight, so the solution here is resolving those alerts during queue clean up cron job.
Closes #855

Fix clean alerts

---

packages/app/components/Queue/Student/StudentQueue.tsx
packages/server/src/question/question.controller.ts
packages/server/test/question.integration.ts

Allows one question per course for each student.
Previously, only one question is allowed per user. We believe it is more ideal to allow a student to have one question per course. This PR also updated the warning for when a student wants to create a second question for a course.
Closes #845 

Allow students to have multiple questions across multiple courses

---

packages/app/components/Today/OpenQueueCard.tsx
packages/app/components/Today/TACheckinButton.tsx
packages/app/pages/course/[cid]/today.tsx
packages/app/styles/global.css

Changes to revamp today page according to Meghan's figma designs.  Also addresses bug where professors couldnt edit queue notes from the today page. 
All changes are cosmetic in nature, no logic changes.
Checked in:
Checked out:
Disabled Questions:
When notes are populated:
Closes #772 
Tested by inspection, might need to fix cypress tests since we arent going with the same queue disabled icon, etc.

New Today Page

---

packages/server/src/resources/resources.controller.ts

Changes how the GET /calendar endpoint returns errors - it wasn't actually returning errors to the request, and was just crashing the backend. I think this was either because it's using a `Response` object instead of directly returning the response, or because the errors were getting thrown within a callback instead of in the actual endpoint function. Anyways this should correctly return errors to the client now (for nonexistent courses, problems with writing to disk, etc)

Fix error handling for calendar fetch

---

packages/app/components/Queue/QueueListSharedComponents.tsx

Button on queue page to allow TAs to clear the queue. Also fixing up some CSS (ty to Venkat for the assistance). 
https://user-images.githubusercontent.com/59672089/164585322-83325223-05f9-4db0-9326-e22e1562635c.mov
Closes #878 
Manually tested -- backend endpoint is already tested. I could write a cypress test, but that may be a bit much.

insert a clear queue button 

---

packages/api-client/index.ts
packages/app/components/Insights/components/SimpleTable.tsx
packages/app/pages/course/[cid]/insights.tsx
packages/common/index.ts
packages/server/src/insights/insight-objects.ts
packages/server/src/insights/insights.controller.ts
packages/server/src/insights/insights.module.ts
packages/server/src/insights/insights.service.spec.ts
packages/server/src/insights/insights.service.ts

Added functionality to insights query that caches the big "Questions Asked" query and allows the result to be paginated/offset. Motivation is to allow frontend to retrieve all data for this insight without requesting it all at once and overloading it. In its current state, the frontend does what it did before and only gets 75 (will be updated in next PR)
Closes #844

Caching + pagination for most questions asked

---

packages/app/components/Nav/NavBar.tsx
packages/server/src/login/login-course.service.ts

Somehow we never caught this, but we weren't saving the ProfSectionGroupsModels after updating them with new section groups from khoury admin. Hence when profs try to register for a new semester, their pending courses aren't there. 

Save pending section groups for returning profs

---

packages/app/components/Today/QueueCheckInModal.tsx

Fixed typo for queue selection placeholder ("Select a course" => "Select a queue")

Select an existing queue typo fix

---

packages/app/components/Queue/TA/TAQueueDetailButtons.tsx

minor case, TAs cant see student text while theyre drafting so it does not make sense for them to ask students to rephrase their question

cannot hit rephrase alert if question status is drafting

---

packages/app/components/Queue/QueueListSharedComponents.tsx

queue text is now scrollable on the queue page. height is 200px max
closes #895
https://user-images.githubusercontent.com/59672089/169447347-919777d8-fce5-4903-8053-dcf2a4d3d554.mov
https://user-images.githubusercontent.com/59672089/169448521-ecd84189-8c0f-436c-81c0-2ddd01603bd1.mov

add scrollbars to queue text

---

cypress/integration/ta/queue_create_inperson_or_online.spec.js
packages/server/src/resources/resources.controller.ts

Based on the logs I added, I think that calendars for old courses are still on our server not because the cron job isn't deleting them properly, but because the calendar endpoints for those courses are somehow still being hit. That causes the server to redownload the files. I'm adding a check in the calendar endpoint to avoid downloading calendars for disabled courses, and just throw a 404 error back at them. Hopefully this should make sure our uploads folder stays clean. 

Don't save cals for disabled courses

---

cypress/integration/common/login.spec.js
cypress/integration/ta/allow_or_disable_questions.spec.js
cypress/integration/ta/edit_queue_notes.spec.js
cypress/integration/ta/queue_check_in_check_out.spec.js
cypress/integration/ta/queue_create_inperson_or_online.spec.js
cypress/utils.js
packages/app/components/Today/SandboxApplication.tsx

I hid the apply modal in percy (but even better, i use local storage to prevent the modals from rendering in the first place)
we still face the issue where we infinitely fetch old calendars though :/
I ran the cyress tests locally 🤯 , and theyll run again in CI 😎

Df/hide apply modal in percy/cypress tests

---

packages/api-client/index.ts
packages/app/components/Settings/CourseAdminPanel.tsx
packages/app/components/Settings/CourseOverrideSettings.tsx
packages/app/components/Settings/CourseRoster.tsx
packages/app/components/Settings/CourseRosterPage.tsx
packages/common/index.ts
packages/server/src/course/course.controller.ts
packages/server/src/course/course.service.spec.ts
packages/server/src/course/course.service.ts

Add new course roster page to course admin panel. Lists professors, TAs, and students in course, and allows admin to search through these lists. Also offers pagination over student list
Also makes change to API so that it sends the total number of students/TAs/professors etc. along with the page of users requested
Closes #866
Tested to make sure API requests + display worked correctly on dev, added ~ 50 dummy students to test pagination/search features
Top of Page display 
Bottom of Page display
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

Course roster page frontend

---

packages/app/components/common/Footer.tsx

no one in sandbox uses monday.com now, so now we have a google form hosted by sandboxneu@gmail.com visible here https://forms.gle/kd1gXq6b1CwbhTNy5 
perk is that sandboxneu@gmail.com gets a email notif whenever this is filled out
its a KOH spring baby
#687 (an oldie that I never got the chance to do)

Update Bug Report Form Link

---

packages/server/src/login/login-course.service.ts
packages/server/test/login.integration.ts
packages/server/test/util/factories.ts

Disable courses from past semesters when the Khoury login payload changes to a previously unseen semester. This eliminates the need for running a manual script; after this, running the app should be completely automatic. 
Generally speaking, each semester disables any other courses which are still enabled, except for some special cases with summer classes. Some summer semesters are concurrent (because of Summer_Full courses), so courses in concurrent semesters do not get disabled. 
Closes #906

Automatically disable past semester courses

---

README.md
packages/app/components/About/AboutPage.tsx
packages/app/pages/about.tsx

Update the ReadMe + About Page descriptions to close down shop here. Removed the small white dog (so as to not confuse people), Angela, and Sumit.
Godspeed folks o7

update readme and about page descriptions
